### ISSUE TITLE
Modpack permission

### ISSUE THREAD

**Issue by KreativeKngYT** [FusionSwarly/Create-Structures#10]
I notice the ARR license and didnt see anything on the Modrinth page about policies for including this mod in modpacks. Are we allowed to use this mod in modpacks? I have a CurseForge modpack I would like to use this mod in and wanted to get your permission.

**Comment by FusionSwarly** [comment]
You have full permission to include this in modpacks on Curseforge. I had originally archived the mod on curseforge to prevent modpacks from breaking but curseforge took the mod down entirely.

**Comment by furtabs** [comment]
Bumped Curseforge, they require at least a license file somewhere on the repo stating this. Could just be a simple license file saying modpacks are allowed to be distributed

**Comment by Cryon-z** [comment]
Can I use this mod in the modpack? I have a modrinth modpack where I want to use this mod and would like your permission.
