### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by SageofTurtles** [FusionSwarly/Create-Structures#11]
Hello, and I apologize for the simple question, but I'm having difficulty figuring this out and can't seem to locate an answer online. Create Structures appears to be both a mod and a data pack. I'd like to install it on my 1.20.1 Fabric server, but do I need to install it as a mod or as a data pack, or some other way entirely?

Thanks in advance!

**Comment by FusionSwarly** [comment]
You can install it as a mod or a datapack. The easiest way to install the mod for a server would be to use the .jar file and put it in the mods folder inside your server. Please note that the mod uses command blocks, so make sure that command blocks are enabled in your server.properties file.
