### ISSUE TITLE
curseforge??

### ISSUE THREAD

**Issue by DariusZeBaguette** [FusionSwarly/Create-Structures#9]
what happened to the curseforge version of the mod? i cant find it anywhere

**Comment by FusionSwarly** [comment]
Curseforge will no longer be supported due to Overwolf's support of the IDF. I originally archived it but it was taken down by curseforge. You can still download the mod from Modrinth.

**Comment by DariusZeBaguette** [comment]
i heard out that overwolf is actually located in israel, so them giving a bit of money to help the country was to protect their employees

**Comment by SkyKingPX** [comment]
Now the problem is that when you download the Mod from Modrinth and create a CurseForge Modpack, CurseForge detects this Mod as „project-871698“ and if you try to publish the Modpack with that Mod, CurseForge will reject it.
@FusionSwarly
